version: "3"

services:
    api:
        build: ./api/
        ports:
            - "3001:3000"
        volumes:
            - "./api:/var/html/www/api"
        links:
            - db
    
    db:
        image: mongo:4.2.3
        ports:
            - "27017:27017"
        volumes:
            - './db:/data/db'
        
    site:
        build: ./site/
        ports: 
            - "3002:3000"
        volumes:
            - "./site:/var/html/www/site"
        links:
            - api